### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by uli-on** [thetwom/Tuner#1]
Hi Michael!
On app start I can see some grid structure for fractions of a second, then the app crashes. The Scoop app extracts this from the logs

`FATAL EXCEPTION: main
Process: de.moekadu.tuner, PID: 13084
android.content.res.Resources$NotFoundException: Resource ID #0x7f080072
	at android.content.res.Resources.getValue(Resources.java:1351)
	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:252)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
	at androidx.appcompat.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:126)
	at androidx.appcompat.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:207)
	at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:188)
	at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
	at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:495)
	at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1176)
	at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
	at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
	at androidx.appcompat.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1090)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:462)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

Tuner v1.2.0 from F-Droid, Vanilla Android 6.0.1, Moto G4

**Comment by thetwom** [comment]
Hi,
thanks a lot for trying the app and reporting the error. I indeed misplaced an icon which caused apps with older Android versions to crash. I already provided a fix, but fdroid takes some days to pick it up. You can also directly test the apk: [v1.2.1](https://github.com/thetwom/Tuner/releases/tag/v1.2.1). 

Please let me know, if this fixes the problem for you. Also let me know if things don't work as expected or if how things are working are annoying :-)

**Comment by uli-on** [comment]
I'll gladly test but constantly get a parsing error, thrown by the
(standard) installer. Another 5¢ help, please.

Am 2. Mai 2021 20:55:38 schrieb thetwom ***@***.***>:

**Comment by thetwom** [comment]
Thanks for testing and sorry to hear that the installation fails. It might be a problem with the signatures I used for the release file. Can you test the following version? [v1.2.2-beta1](https://github.com/thetwom/Tuner/releases/tag/v1.2.2-beta1)

Please make sure to uninstall any old version before installing the new one. But I guess, that's what your already did ...

**Comment by uli-on** [comment]
> Please make sure to uninstall any old version before installing the new one. But I guess, that's what your already did ...
> 

Yup, as you guessed. Alright, this version does not throw stones at us :)

But I'm afraid I can't be of much help testing the app other than a normal "person with no knowledge of the data displayed". I'd hoped it would have something like a simple mode (like e.g. Tunerly from F-Droid) but I didn't shy back from the more scientific look of the supplied screenshots cause I love testing apps in general. I always profit from that. And hence I gladly test what i can judge.

What I can tell from that limited POV is not more than "All three graphs are moving even on my aged Android." Yay!

Few things could be improved:
- The color of the menu bar is a light gray for night mode, which is divergent from the screenshots. But apart from that small detail you did a proper job in the color handling department of night/day mode. 
- The app might profit from a screen lock blocker. Mine is set to 1 min, and though it's more than enough for most apps when you have the fingers on the screen, it's definitely too little to watch all these graphs with an instrument in your hands. At least from my beginner's position. 
- Less annoying but a mute function might also be useful while the app is active.

Question: What is that window function thing, is it supposed to have a visible effect?

**Comment by thetwom** [comment]
Thanks a lot for your feedback. Good to hear that the app works now for you.

I agree that the currently more scientific appearance might not be ideal for the standard user since the top two graphs are of no real interest while tuning. However, during tests they were quite helpful and since the visual space is available, I kept them for now. Maybe I will add a simpler mode in future. 

Regarding your comments:
- Color of the menu bar in night mode: Interesting note. Can you add a screenshot? Since for me it all looks as in the screenshots and I wonder where the difference comes from.
- I indeed thought that blocking the screen is not necessary, but maybe it is indeed helpful. I can at least add it as an option.
- With "mute function" you mean to mute the android phone? This is something I would not like to add since it quickly can become annoying when the app mutes your audio e.g. by accidentally starting it. I think it's better if the users use the android mute function ...

The windowing function is not having a visual effect, but is a mathematical function to extract data from the recorded audio stream. It can influence the tuning performance, but my tests only show a minor influence.

**Comment by uli-on** [comment]
I hope adding a screenshot to a mail reply works here, not yet tried.

**Comment by uli-on** [comment]
OK, wanted to avoid the two devices verification dance.

![Tuner-Menu-Night-Mode](https://user-images.githubusercontent.com/35634829/117048743-9d4d3a00-ad13-11eb-9ba4-42aabe6c318e.png)

**Comment by thetwom** [comment]
thanks a lot for the screenshot. Now I understand what you mean: The light gray of the status bar (where e.g. the wifi connection is shown). In the screenshots I only cut out the app window, so there you cannot see this status bar.

Indeed, I didn't even try to change the color of the status bar within the app, but a quick research revealed that this indeed follows some rules ... I decided to make it black now for both light and dark theme ... hoping that this is what makes most sense ...

Thanks for the hint which made me looking into that.

**Comment by uli-on** [comment]
Am 05.05.2021 um 08:12 schrieb thetwom ***@***.***>:
> The light gray of the status bar
> 

Right, "status bar"! Every day you <del>learn</del><ins>forget</ins> something new!

**Comment by thetwom** [comment]
I think this issue is solved, so I will close it. Thanks again for reporting!
